import React from 'react';
import FuturedCategory from './FuturedCategory';
import Categorie from './Categorie';

const IndexCategorie = () => {
    return (
        // {
        //         <div>
        //             <FuturedCategory />
        //             <div className="bg-gray-100 lg:py-16 py-10">
        //                 <div className="mx-auto max-w-screen-2xl px-3 sm:px-10">

        //                     <ul className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-6">
        //                         <li className="group">
        //                             <div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer 
        //             transition duration-200 ease-linear transform group-hover:shadow-lg">
        //                                 <div className="flex items-center">
        //                                     <div>
        //                                         <img alt="category" width="35" height="35" decoding="async" data-nimg="1"
        //                                             srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv16550970
        //             02%2Fplaceholder_kvepfp.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.
        //             com%2Fahossain%2Fimage%2Fupload%2Fv1655097002%2Fplaceholder_kvepfp.png&amp;w=96&amp;q=75 2x"
        //                                             src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1655097002
        //              %2Fplaceholder_kvepfp.png&amp;w=96&amp;q=75" style={{ color: "transparent" }} />
        //                                     </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight 
        //              line-clamp-1  group-hover">
        //                                         rose</h3>
        //                                         <ul className="pt-1 mt-1">
        //                                         </ul></div></div></div>
        //                         </li><li className="group">
        //                             <div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer 
        //              transition duration-200 ease-linear transform group-hover:shadow-lg">
        //                                 <div className="flex items-center"><div><img alt="category" loading="lazy"
        //                                     width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fre
        //              s.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fcarp-fish_paxz
        //              rt.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fima
        //              ge%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fcarp-fish_paxzrt.png&amp;w=96&amp;q=75 2x"
        //                                     src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv16583407
        //              05%2Fcategory%2520icon%2Fcarp-fish_paxzrt.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} /></div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Fish &amp; Meat</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer">
        //                                         <span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Fish</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer">
        //                                             <span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Meat</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg">
        //                                                 <div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcategory%2520icon%2Fcabbage_n59uv3.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcategory%2520icon%2Fcabbage_n59uv3.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcategory%2520icon%2Fcabbage_n59uv3.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                 </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Fruits &amp; Vegetable</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Baby Food</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Fresh Fruits</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Dry Fruits</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div>
        //                                                     <img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcategory%2520icon%2Ffrying-pan_vglm5c.png&amp;w=48&amp;q=75 1x, 
        //              /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcatego
        //              ry%2520icon%2Ffrying-pan_vglm5c.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudi
        //              nary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340704%2Fcategory%2520icon%2Ffrying-pan_vglm5c.png&amp;w=96&
        //              mp;q=75" style={{ color: "transparent;" }} /></div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Cooking Essentials</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Flour</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer">
        //                                                         <span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Oil</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fcookie_1_ugipqa.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fcookie_1_ugipqa.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fcookie_1_ugipqa.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} /></div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Biscuits &amp; Cakes</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Biscuits</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Cakes</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div>
        //                                                             <img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fspray_pebsjt.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fspray_pebsjt.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fspray_pebsjt.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Household Tools</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Water Filter</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Cleaning Tools</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Pest Control</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340707%2Fcategory%2520icon%2Fcat_tznwmq.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340707%2Fcategory%2520icon%2Fcat_tznwmq.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340707%2Fcategory%2520icon%2Fcat_tznwmq.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Pet Care</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Dog Care</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Cat Care</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fbeauty_vfbmzc.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fbeauty_vfbmzc.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fbeauty_vfbmzc.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Beauty &amp; Healths</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Women</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Men</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fi.postimg.cc%2FrmLvfsMC%2Fstrawberry-jam-1.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fi.postimg.cc%2FrmLvfsMC%2Fstrawberry-jam-1.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fi.postimg.cc%2FrmLvfsMC%2Fstrawberry-jam-1.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Jam &amp; Jelly</h3><ul className="pt-1 mt-1"></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fmilk_dcl0dr.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fmilk_dcl0dr.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340706%2Fcategory%2520icon%2Fmilk_dcl0dr.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Milk &amp; Dairy</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Butter &amp; Ghee</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Ice Cream</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Dairy</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div><img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fjuice_p5gv5k.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fjuice_p5gv5k.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fjuice_p5gv5k.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4"><h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1  group-hover">Drinks</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Tea</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Water</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Juice</a></li></ul></div></div></div></li><li className="group"><div className="flex w-full h-full border border-gray-100 shadow-sm bg-white p-4 cursor-pointer transition duration-200 ease-linear transform group-hover:shadow-lg"><div className="flex items-center"><div>
        //                                                             <img alt="category" loading="lazy" width="35" height="35" decoding="async" data-nimg="1" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fbagel_mt3fod.png&amp;w=48&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fbagel_mt3fod.png&amp;w=96&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fahossain%2Fimage%2Fupload%2Fv1658340705%2Fcategory%2520icon%2Fbagel_mt3fod.png&amp;w=96&amp;q=75" style={{ color: "transparent;" }} />
        //                                                         </div><div className="pl-4">
        //                                                                 <h3 className="text-sm text-gray-600 font-serif font-medium leading-tight line-clamp-1 
        //              group-hover">Breakfast</h3><ul className="pt-1 mt-1"><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Bread</a></li><li className="pt-1"><a className="flex items-center font-serif text-xs text-gray-400 cursor-pointer"><span className="text-xs text-gray-400 "><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke-linecap="square" stroke-miterlimit="10" stroke-width="48" d="M184 112l144 144-144 144"></path></svg></span>Cereal</a></li></ul></div></div></div></li></ul></div></div>

        //         </div>
        //         }
        <div></div>
    );
}

export default IndexCategorie;
